layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

bio: "Besides that, I enjoy gardening, reading, and writing short stories.
"

about: "I'm Yasaman, a Ph.D. student at <a href=\"https://uci.edu/\">the University of Calirofnia, Irvine</a> working with <a href=\"https://sameersingh.org/\">Prof. Sameer Singh</a>.
My research interests lie primarily in Natural Language Processing.
I'm interested in using language models under few-shots settings to solve common-sense reasoning problems.
I am currently a student researcher at DeepMind.
"

email: yrazeghi@uci.edu

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: yasaman-razeghi-a1a909160
  github: yasamanrazeghi7
  scholar: YCtmdaMAAAAJ
  # mastodon: your_username
  # medium: noidsirius
  # stackoverflow: 2681272/noidsirius
  # telegram: your_username
  twitter: yasaman_razeghi
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

work:
  - company: "University of California, Irvine"
    company_url: "http://seal.ics.uci.edu/"
    role: "Graduate Research Assistant"
    start: "October 2017"
    end: "Present"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Designed and created novel testing techniques to detect accessibility and delivery issues in android apps </li>
      <li> Devised a scalable and accurate static analysis technique to detect event races </li>
      <li> Investigated light-weight model checkers to formally analyze uncertainty in models </li>
    </ul>"
  - company: "Microsoft Research"
    company_url: ""
    role: "Research Intern"
    start: "June 2021"
    end: "September 2021"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Designed a multi-level job caching mechanism, improved the response time +30 times faster than the baseline model</li>
      <li> Implemented a scalable caching service using ASP.NET, CosmosDB, and Azure Storage </li>
    </ul>"
  - company: "Avaye Hamrah Hooshmand Hezardastan"
    company_url: "https://cafebazaar.ir/about?l=en"
    role: "Software Engineer"
    start: "October 2015"
    end: "August 2017"
    description: "<ul class='text-gray mb-2 ws-normal pl-3'>
      <li> Coordinated a number of teams (with 6 to 11 members) in CafeBazaar, a local Android app market, to create tools for developers </li>
      <li> Established a developers panel based on microservice architecture (using Django, Docker, and Kubernetes) </li>
      <li> Redesigned and developed a system to automate the process of filtering out malwares and low-quality apps </li>
      <li> Inspected technical teams' performance issues at a company-wide level </li>
    </ul>"


publication:
  - name: "Snoopy: An Online Interface for Exploring the Effect of Pretraining Term Frequencies on Few-Shot LM Performance"
    authors: "<u>Yasaman Razeghi</u>, Raja Sekhar Reddy Mekala, Robert L Logan Iv, Matt Gardner, Sameer Singh"
    conference: "Proceedings of the The 2022 Conference on Empirical Methods in Natural Language Processing: System Demonstrations"
    pdf: "https://aclanthology.org/2022.emnlp-demos.39.pdf"
  - name: "A theoretically grounded benchmark for evaluating machine commonsense"
    authors: "Henrique Santos, Ke Shen, Alice M Mulvehill, <u>Yasaman Razeghi</u>, Deborah L McGuinness, Mayank Kejriwal"
    conference: "arXiv"
    pdf: "https://arxiv.org/abs/2202.07206"
  - name: "Impact of Pretraining Term Frequencies on Few-Shot Reasoning"
    authors: "<u>Yasaman Razeghi</u>, Robert L. Logan IV, Matt Gardner, Sameer Singh"
    conference: "arXiv"
    pdf: "https://arxiv.org/abs/2202.07206"
  - name: "Deep Bucket Elimination"
    authors: "<u>Yasaman Razeghi</u>, Kalev Kask, Yadong Lu, P. Baldi, Sakshi Agarwal, and R. Dechter"
    conference: "<strong>IJCAI 2021</strong>, Proceedings of the International Joint Conferences on Artificial Intelligence, August 2021"
    pdf: "https://www.ijcai.org/proceedings/2021/0582.pdf"
  - name: "Deriving Behavioral Tests from Common Sense Knowledge Graphs"
    authors: "<u>Yasaman Razeghi</u>, Robert L. Logan IV, and Sameer Singh"
    conference: "<strong>CSKG 2021</strong>, AAAI Workshop on Common Sense Knowledge Graphs, February 2021"
    pdf: "https://usc-isi-i2.github.io/AAAI21workshop/papers/Razeghi_CSKGsAAAI-21.pdf"
  - name: "AutoPrompt: Eliciting Knowledge from Language Models with Automatically Generated Prompts"
    authors: "Taylor Shin*, <u>Yasaman Razeghi*</u>, Robert L. Logan IV*, Eric Wallace, and Sameer Singh"
    conference: "<strong>EMNLP 2020</strong>, Empirical Methods in Natural Language Processing, November 2020"
    video: "https://www.youtube.com/watch?v=rWOtAI4BClM"
    repo: "https://github.com/ucinlp/autoprompt"
    pdf: "https://arxiv.org/pdf/2010.15980.pdf"


  # - name: Ben ;
  #  video: https://youtu.be/eSkozhtT-9o
    # pdf: http://seal.ics.uci.edu/publications/2020_MobiSys_BenchERoid.pdf

    # pdf: http://seal.ics.uci.edu/publications/2020_ASE_Empirical.pdf

  # - name: B
  #   description: A Static Analysis Framework for Accurate and Scalable Event-Race Detection in Android
  #   html_url: https://github.com/seal-hub/ERCatcher
  #
  # - name: C
  #   description: A Micro-Benchmark for Event Races in Android
  #   html_url: https://github.com/seal-hub/bencheroid


projects:
  - name: SootTutorial
    description: A step-by-step tutorial for Soot, a Java and Android static analysis framework
    html_url: https://github.com/noidsirius/SootTutorial
    source: github

  - name: Translation
    description: A web app designed to translate contest questions of the International Olympiad in Informatics (IOI 2017)
    html_url: https://github.com/ioi-2017/translation
    source: github

  - name: BlackBox Testing Sandbox
    description: A simple tool emulating the black-box testing, used in the Introduction to Software Engineering course in UCI
    html_url: https://github.com/noidsirius/BlackBoxTestingDemo
    source: github

  - name: Descrete Mathematic Contest
    description:  An online contest platform applying active learning techniques for mathematic courses
    html_url: https://web.archive.org/web/20170505122033/http://acm.ut.ac.ir/acm/posts/190
    source: other

  - name: Vahed
    description: A Ruby on Rails web app for students in University of Tehran to schedule their courses in the following semester
    html_url: https://web.archive.org/web/20170505130936/http://acm.ut.ac.ir/acm/posts/158
    source: other





topics:
  - name: Python

  - name: Program Analysis

  - name: Machine Learning

  - name: Agile (Scrum)

  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
    description: I learned something I learned something I learned something I learned something

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
